branches:
  only:
    - master

language: node_js

node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - git config --global user.name "frostrain"
  - git config --global user.email "frostrain@outlook.com"
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # 安装 emacs
  - make -f emacs-travis.mk install_emacs

install:
  - npm install

script:
  - hexo g
# 提交生成的 静态html 到github的pages
after_script:
  - cd public
  - git init
  - git add --all .
  - git commit --message "Automatically build from travis-ci"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

env:
  global:
    - GH_REF=github.com/frostrain/blog.git
    - EMACS_VERSION=24.5