branches:
  only:
    - master

language: node_js

sudo: false

node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - git config --global user.name "frostrain"
  - git config --global user.email "frostrain@outlook.com"

install:
  - npm install

script:
  - hexo g

after_script:
  - cd public
  - git init
  - git add --all .
  - git commit --message "Automatically build from travis-ci"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

env:
  global:
    - GH_REF: github.com/frostrain/blog.git